# Generated by Django 4.2.24 on 2025-09-05 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('job', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=100)),
                ('pay', models.IntegerField()),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
